### ISSUE TITLE
migration error

### ISSUE THREAD

**Issue by mshanak** [sgpatil/orientdb-laravel-5#16]
when i run 
`php artisan orient:migrate`

*_the following error *_

```

 [Sgpatil\Orientphp\Exception]                                                                                                                                                
  com.orientechnologies.orient.core.exception.OQueryParsingException: Error on parsing command at position #0: Error on parsing query                                          
  Query:  migrations                                                                                                                                                           
  ------^                                                                                                                                                                      
  --> com.orientechnologies.orient.core.exception.OCommandExecutionException: Class 'MIGRATIONS' was not found in current database#0 /var/www/html/academicmultisite/vendor/s  
  gpatil/orientdb-php/src/Sgpatil/Orientphp/Transport.php(126): Sgpatil\Orientphp\Transport\Curl->makeRequest('POST', '', Array)                                               
  #1 /var/www/html/academicmultisite/vendor/sgpatil/orientdb-php/src/Sgpatil/Orientphp/Command.php(67): Sgpatil\Orientphp\Transport->post('', Array, '/batch/ppustaff')        
  #2 /var/www/html/academicmultisite/vendor/sgpatil/orientdb-php/src/Sgpatil/Orientphp/Client.php(904): Sgpatil\Orientphp\Command->execute()                                   
  #3 /var/www/html/academicmultisite/vendor/sgpatil/orientdb-php/src/Sgpatil/Orientphp/Client.php(237): Sgpatil\Orientphp\Client->runCommand(Object(Sgpatil\Orientphp\Command  
  \ExecuteBatchQuery))                                                                                                                                                         
  #4 /var/www/html/academicmultisite/vendor/sgpatil/orientdb-php/src/Sgpatil/Orientphp/Batch/Query.php(58): Sgpatil\Orientphp\Client->executeBatchQuery(Object(Sgpatil\Orient  
  php\Batch\Query))                                                                                                                                                            
  #5 /var/www/html/academicmultisite/vendor/sgpatil/oriquent/src/Sgpatil/Orientdb/Schema/OrientdbBuilder.php(15): Sgpatil\Orientphp\Batch\Query->getResultSet()                
  #6 /var/www/html/academicmultisite/vendor/sgpatil/oriquent/src/Sgpatil/Orientdb/Migrations/DatabaseMigrationRepository.php(137): Sgpatil\Orientdb\Schema\OrientdbBuilder->h  
  asTable('migrations')                                                                                                                                                        
  #7 /var/www/html/academicmultisite/vendor/sgpatil/oriquent/src/Sgpatil/Orientdb/Migrations/Migrator.php(378): Sgpatil\Orientdb\Migrations\DatabaseMigrationRepository->repo  
  sitoryExists()                                                                                                                                                               
  #8 /var/www/html/academicmultisite/vendor/sgpatil/oriquent/src/Sgpatil/Orientdb/Console/Migrations/MigrateCommand.php(102): Sgpatil\Orientdb\Migrations\Migrator->repositor  
  yExists()                                                                                                                                                                    
  #9 /var/www/html/academicmultisite/vendor/sgpatil/oriquent/src/Sgpatil/Orientdb/Console/Migrations/MigrateCommand.php(61): Sgpatil\Orientdb\Console\Migrations\MigrateComma  
  nd->prepareDatabase()                                                                                                                                                        
  #10 [internal function]: Sgpatil\Orientdb\Console\Migrations\MigrateCommand->fire()                                                                                          
  #11 /var/www/html/academicmultisite/bootstrap/cache/compiled.php(1232): call_user_func_array(Array, Array)                                                                   
  #12 /var/www/html/academicmultisite/vendor/laravel/framework/src/Illuminate/Console/Command.php(169): Illuminate\Container\Container->call(Array)                            
  #13 /var/www/html/academicmultisite/vendor/symfony/console/Command/Command.php(256): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput),  
   Object(Symfony\Component\Console\Output\ConsoleOutput))                                                                                                                     
  #14 /var/www/html/academicmultisite/vendor/laravel/framework/src/Illuminate/Console/Command.php(155): Symfony\Component\Console\Command\Command->run(Object(Symfony\Compone  
  nt\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))                                                                                         
  #15 /var/www/html/academicmultisite/vendor/symfony/console/Application.php(791): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(  
  Symfony\Component\Console\Output\ConsoleOutput))                                                                                                                             
  #16 /var/www/html/academicmultisite/vendor/symfony/console/Application.php(186): Symfony\Component\Console\Application->doRunCommand(Object(Sgpatil\Orientdb\Console\Migrat  
  ions\MigrateCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))                                             
  #17 /var/www/html/academicmultisite/vendor/symfony/console/Application.php(117): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvIn  
  put), Object(Symfony\Component\Console\Output\ConsoleOutput))                                                                                                                
  #18 /var/www/html/academicmultisite/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(107): Symfony\Component\Console\Application->run(Object(Symfony\C  
  omponent\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))                                                                                   
  #19 /var/www/html/academicmultisite/artisan(36): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\C  
  onsole\Output\ConsoleOutput))                                                                                                                                                
  #20 {main}                                                                                                                                                                   

```

**Comment by sgpatil** [comment]
HI @mshanak , have you tried to install migration. As it seems from error that the class `Migration` does not exist in your database. Try to run `php artisan orient:install`.

**Comment by mshanak** [comment]
php artisan orient:install. 
fixed the problem
